version: "3.9"
services:
  app:
    build:
      context: round-up
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "80:8080"
    volumes:
      - ./swagger/openSpec.yaml:/openSpec.yaml
    environment:
      SWAGGER_JSON: /openSpec.yaml